import Container from "@/components/common/Container";
import ReleaseDate from "@/components/news/releaseDate";
import { getArticleByIndex } from "@/lib/news";
import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function NewsLayout({
  children,
  params: { index },
}: Readonly<{
  children: React.ReactNode;
  params: { index: string };
}>) {
  const article = getArticleByIndex(parseInt(index));

  if (!article) {
    return notFound();
  }

  return (
    <Container className="mx-auto max-w-[700px]">
      <div className="flex flex-col gap-4">
        <Image
          src={article.imgSrc}
          alt={article.title}
          width={700}
          height={290}
          className="object-cover rounded-md mt-20"
        />
        <div>
          <ReleaseDate date={article.date} />
          <h1 className="~text-xl/xl-clamped font-bold font-rubik leading-[1.2]">
            {article.title}
          </h1>
          <p className="text-md font-inter ">{article.description}</p>
        </div>
        <div className="h-[1px] w-full bg-c-primary" />
        <div className="h-[1px]" />
      </div>
      <article className="prose prose-invert font-inter prose-headings:font-rubik lg:prose-lg min-h-screen w-full">
        {children}
      </article>
    </Container>
  );
}
